import { ReactNode } from "react";
import { Inter } from "next/font/google";
import Head from "next/head";
import { CartProvider } from "./components/CartContext"; // Ensure the correct path
import "../../public/css/bootstrap.min.css";
import "../../public/css/animate.min.css";
// import "../../public/css/jquery-ui.min.css";
import "../../public/css/meanmenu.min.css";
import "../../public/lib/css/nivo-slider.css";
import "../../public/lib/css/preview.css";
import "../../public/css/slick.min.css";
import "../../public/css/lightbox.min.css";
import "../../public/css/material-design-iconic-font.css";
import "../../public/css/default.css";
import "../../public/style.min.css";
import "../../public/css/shortcode.css";
import "../../public/css/responsive.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <Head>
        <title>My App</title>
      </Head>
      <body className={inter.className}>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
